language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t irishjimdegriz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true irishjimdegriz/react-test npm test

after_success:
  - docker build -t irishjimdegriz/multi-client ./client
  - docker build -t irishjimdegriz/multi-nginx ./nginx
  - docker build -t irishjimdegriz/multi-server ./server
  - docker build -t irishjimdegriz/multi-worker ./worker

