language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t irishjimdegriz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true irishjimdegriz/react-test npm test

after_success:
  - docker build -t irishjimdegriz/multi-client ./client
  - docker build -t irishjimdegriz/multi-nginx ./nginx
  - docker build -t irishjimdegriz/multi-server ./server
  - docker build -t irishjimdegriz/multi-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker hub
  - docker push irishjimdegriz/multi-client
  - docker push irishjimdegriz/multi-nginx
  - docker push irishjimdegriz/multi-server
  - docker push irishjimdegriz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  end: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-245471067308"
  bucket_path: "docker-multi"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
